import Header from "./_components/Header.svelte";
import Footer from "./_components/Footer.svelte";
import Pokerow from "./_components/Pokerow.svelte";
import MoveRow from "./_components/MoveRow.svelte";
import PageTransitions from "./_components/PageTransitions.svelte";

import PokemonPage from "./_components/PokemonPage/PokemonPage.svelte";
import TypeEffectivenessBlock from "./_components/PokemonPage/TypeEffectivenessBlock.svelte"

export {
    Header,
    Footer,
    Pokerow,
    MoveRow,
    PageTransitions,

    PokemonPage,
    TypeEffectivenessBlock
};

export interface IPokemon {
    DexNum: string,
    Name:   string,
    Sprite: string,
    Types:  string,
    Stats: Array<string>;
}

export interface IMove {
    ID: string,
    Name: string,
    Type: string,
    DamageClass: string,
    Power: string,
    Accuracy: string,
    Description: string
}

export interface IAbility {
    ID: string,
    Name: string,
    Description: string
}

export const TypeColors: any = {
    "bug"       : "#a8b820",
    "dark"      : "#705848",
    "dragon"    : "#7038f8",
    "electric"  : "#f8d030",
    "fairy"     : "#ee99ac",
    "fighting"  : "#c03028",
    "fire"      : "#f08030",
    "flying"    : "#a890f0",
    "ghost"     : "#705898",
    "grass"     : "#78c850",
    "ground"    : "#e0c068",
    "ice"       : "#98d8d8",
    "normal"    : "#a8a878",
    "poison"    : "#a040a0",
    "psychic"   : "#f85888",
    "rock"      : "#8d741f",
    "steel"     : "#d9d9f6",
    "water"     : "#6890f0"
}

export const TypeEffectiveness: any = {
    "bug"       : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "dark"      : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "dragon"    : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "electric"  : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "fairy"     : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "fighting"  : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "fire"      : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "flying"    : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "ghost"     : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "grass"     : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "ground"    : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "ice"       : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "normal"    : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "poison"    : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "psychic"   : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "rock"      : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "steel"     : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
    "water"     : {
        "bug"       : "",
        "dark"      : "",
        "dragon"    : "",
        "electric"  : "",
        "fairy"     : "",
        "fighting"  : "",
        "fire"      : "",
        "flying"    : "",
        "ghost"     : "",
        "grass"     : "",
        "ground"    : "",
        "ice"       : "",
        "normal"    : "",
        "poison"    : "",
        "psychic"   : "",
        "rock"      : "",
        "steel"     : "",
        "water"     : ""
    },
}